databases:
  - name: young-professionals-db
    plan: free
    databaseName: young_professionals
    user: young_professionals

services:
  - type: web
    name: young-professionals
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn young_professionals.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: young-professionals-db
          property: connectionString
