# Generated by Django 5.2.13 on 2026-05-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_social_media_icon'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sectionimage',
            new_name='data_manage_content_0b5851_idx',
            old_name='data_manage_content_idx',
        ),
    ]
