# Generated by Django 5.2.13 on 2026-05-12 07:40

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_rename_data_manage_content_idx_data_manage_content_0b5851_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='data/team/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('email_url', models.CharField(blank=True, help_text='Use a mailto: link, e.g. "mailto:name@example.com".', max_length=255)),
                ('view_profile_text', models.CharField(blank=True, max_length=80)),
                ('view_profile_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ('order', 'id'),
            },
        ),
    ]
