# Generated by Django 5.2.13 on 2026-05-07 06:46

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about_us/hero/backgrounds/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
            ],
            options={
                'verbose_name': 'About Us Hero Section',
                'verbose_name_plural': 'About Us Hero Section',
            },
        ),
    ]
