# Generated by Django 5.2.13 on 2026-05-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsMissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Us Mission Section',
                'verbose_name_plural': 'About Us Mission Section',
            },
        ),
        migrations.CreateModel(
            name='AboutUsMissionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about_us.aboutusmissionsection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
