# Generated by Django 5.2.13 on 2026-05-07 07:42

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_share_mission_stats_with_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmissionsection',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/mission/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension]),
        ),
    ]
