# Generated by Django 5.2.13 on 2026-05-07 07:51

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_mission_side_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsFounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('founder_name', models.CharField(blank=True, max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('founder_message', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='about_us/founder/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
            ],
            options={
                'verbose_name': 'About Us Founder Section',
                'verbose_name_plural': 'About Us Founder Section',
            },
        ),
    ]
