# Generated by Django 5.2.13 on 2026-05-07 08:00

import django.db.models.deletion
import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_founder_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsValuesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'About Us Values Section',
                'verbose_name_plural': 'About Us Values Section',
            },
        ),
        migrations.CreateModel(
            name='AboutUsValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about_us/values/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('label', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='about_us.aboutusvaluessection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
