# Generated by Django 5.2.13 on 2026-05-07 09:54

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_journey_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='about_us/pledge/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
            ],
            options={
                'verbose_name': 'About Us Pledge Section',
                'verbose_name_plural': 'About Us Pledge Section',
            },
        ),
    ]
