# Generated by Django 5.2.13 on 2026-05-07 10:00

import django.db.models.deletion
import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_pledge_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsTeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'About Us Team Section',
                'verbose_name_plural': 'About Us Team Section',
            },
        ),
        migrations.CreateModel(
            name='AboutUsTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about_us/team/profiles/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('name', models.CharField(blank=True, max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('email_icon', models.ImageField(blank=True, null=True, upload_to='about_us/team/icons/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('email_url', models.CharField(blank=True, help_text='Use a mailto: link, e.g. "mailto:name@example.com".', max_length=255)),
                ('view_profile_text', models.CharField(blank=True, max_length=80)),
                ('view_profile_url', models.URLField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='about_us.aboutusteamsection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
