# Generated by Django 5.2.13 on 2026-05-07 10:09

import django.db.models.deletion
import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_team_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'About Us Community Section',
                'verbose_name_plural': 'About Us Community Section',
            },
        ),
        migrations.CreateModel(
            name='AboutUsCommunityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/community/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('name', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='about_us.aboutuscommunitysection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
