# Generated by Django 5.2.13 on 2026-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0010_community_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSocialMediaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'About Us Social Media Section',
                'verbose_name_plural': 'About Us Social Media Section',
            },
        ),
    ]
