# Generated by Django 5.2.13 on 2026-05-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0014_social_media_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusteammember',
            name='email_icon',
        ),
    ]
