# Generated by Django 5.2.13 on 2026-05-12 07:44

from django.db import migrations, models


def copy_inline_members_to_data(apps, schema_editor):
    """Copy existing inline `AboutUsTeamMember` rows into the shared
    `data_management.TeamMember` table and pre-select them on the
    About Us Team section so the public page keeps rendering the same
    people it did before."""
    AboutUsTeamMember = apps.get_model("about_us", "AboutUsTeamMember")
    AboutUsTeamSection = apps.get_model("about_us", "AboutUsTeamSection")
    TeamMember = apps.get_model("data_management", "TeamMember")

    legacy = list(AboutUsTeamMember.objects.order_by("order", "id"))
    if not legacy:
        return

    new_ids = []
    for row in legacy:
        new_row = TeamMember.objects.create(
            name=row.name or "",
            profile_image=row.profile_image,
            designation=row.designation or "",
            email_url=row.email_url or "",
            view_profile_text=row.view_profile_text or "",
            view_profile_url=row.view_profile_url or "",
            order=row.order,
        )
        new_ids.append(new_row.pk)

    section = AboutUsTeamSection.objects.first()
    if section is not None:
        section.selected_team_members.set(new_ids)


def noop_reverse(apps, schema_editor):
    """Reverse: leave the new TeamMember rows in place."""


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0015_remove_aboutusteammember_email_icon'),
        ('data_management', '0009_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusteamsection',
            name='selected_team_members',
            field=models.ManyToManyField(blank=True, related_name='about_us_team_sections', to='data_management.teammember'),
        ),
        migrations.RunPython(copy_inline_members_to_data, noop_reverse),
        migrations.DeleteModel(
            name='AboutUsTeamMember',
        ),
    ]
