# Generated by Django 5.2.13 on 2026-04-28 11:50

import django.db.models.deletion
import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.ImageField(upload_to='home/features/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('background_image', models.ImageField(upload_to='home/hero/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('primary_button_text', models.CharField(blank=True, max_length=60)),
                ('primary_button_url', models.URLField(blank=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=60)),
                ('secondary_button_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name', models.CharField(max_length=160)),
                ('job_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home/opportunities/banners/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/opportunities/logos/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('salary_type', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('stipend', 'Stipend'), ('unpaid', 'Unpaid / Volunteer')], max_length=20)),
                ('apply_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities / Jobs',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(help_text='Headline number, e.g. "600,000+"', max_length=40)),
                ('subtitle', models.CharField(help_text='Label, e.g. "Students"', max_length=80)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats (Our Network)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='home/testimonials/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('menu_name', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='Absolute (https://...) or relative (/about) path.', max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent menu — enables nested dropdowns.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Menu',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
