# Generated by Django 5.2.13 on 2026-04-29 11:42

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='home/hero/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('hero_button_text', models.CharField(blank=True, max_length=60)),
                ('hero_button_url', models.URLField(blank=True)),
                ('feature_icon', models.ImageField(blank=True, null=True, upload_to='home/features/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('feature_title', models.CharField(blank=True, max_length=120)),
                ('feature_description', models.TextField(blank=True)),
                ('stat_title', models.CharField(blank=True, help_text='Headline number, e.g. "600,000+"', max_length=40)),
                ('stat_subtitle', models.CharField(blank=True, help_text='Label, e.g. "Students"', max_length=80)),
                ('testimonial_name', models.CharField(blank=True, max_length=120)),
                ('testimonial_designation', models.CharField(blank=True, max_length=160)),
                ('testimonial_message', models.TextField(blank=True)),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='home/testimonials/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('job_company_name', models.CharField(blank=True, max_length=160)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('job_logo', models.ImageField(blank=True, null=True, upload_to='home/opportunities/logos/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('job_banner_image', models.ImageField(blank=True, null=True, upload_to='home/opportunities/banners/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('job_apply_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.RemoveField(
            model_name='navigationmenu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='NavigationMenu',
        ),
    ]
