# Generated by Django 5.2.13 on 2026-04-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_drop_legacy_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='about_section_is_active',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='feature_1_is_active',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='feature_2_is_active',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='feature_3_is_active',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='feature_4_is_active',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='feature_5_is_active',
        ),
    ]
