# Generated by Django 5.2.13 on 2026-04-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_feature_shared_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle',
        ),
    ]
