# Generated by Django 5.2.13 on 2026-05-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_aboutsection_id_alter_applysection_id_and_more'),
        ('home', '0020_social_media'),
    ]

    operations = [
    ]
