# Generated by Django 5.2.13 on 2026-05-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20260501_1854'),
        ('home', '0021_testimonials'),
    ]

    operations = [
    ]
