# Generated by Django 5.2.13 on 2026-05-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_0021_merge_20260501_1854_0021_testimonials'),
        ('home', '0022_testimonials_title'),
    ]

    operations = [
    ]
