# Generated by Django 5.2.13 on 2026-05-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_app_section'),
        ('home', '0023_merge_20260501_1929'),
    ]

    operations = [
    ]
