# Generated by Django 5.2.13 on 2026-05-06 10:15

import home.storage
import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_network_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksection',
            name='network_section_video',
            field=models.FileField(blank=True, null=True, storage=home.storage.video_storage, upload_to='home/network/', validators=[home.validators.validate_video_size, home.validators.validate_video_extension]),
        ),
    ]
