# Generated by Django 5.2.13 on 2026-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_testimonial_users_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasection',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialmediasection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
