# Generated by Django 5.2.13 on 2026-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_social_media_label_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpoolsection',
            name='talent_pool_section_label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
