# Generated by Django 5.2.13 on 2026-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_social_media_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='bottom_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='herosection',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5 (e.g. 4.8).', max_digits=3, null=True),
        ),
    ]
