# Generated by Django 5.2.13 on 2026-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_rename_data_manage_content_idx_data_manage_content_0b5851_idx'),
        ('home', '0039_herosection_bottom_note_herosection_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysection',
            name='selected_employers',
            field=models.ManyToManyField(blank=True, related_name='apply_sections', to='data_management.employer'),
        ),
    ]
