# Generated by Django 5.2.13 on 2026-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_applysection_selected_employers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsection',
            name='bottom_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
