# Generated by Django 5.2.13 on 2026-05-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('search_placeholder', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Insight Hero Section',
                'verbose_name_plural': 'Insight Hero Section',
            },
        ),
    ]
