# Generated by Django 5.2.13 on 2026-05-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightFounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_1', models.CharField(blank=True, max_length=120)),
                ('label_2', models.CharField(blank=True, max_length=120)),
                ('date_label', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('meta_data', models.CharField(blank=True, max_length=160)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Insight Founder Section',
                'verbose_name_plural': 'Insight Founder Section',
            },
        ),
        migrations.CreateModel(
            name='InsightFounderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_entries', to='insight.insightfoundersection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
