# Generated by Django 5.2.13 on 2026-05-12 05:42

import django.db.models.deletion
import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_insightfoundersection_insightfoundercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('card_button_text', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Insight Article Section',
                'verbose_name_plural': 'Insight Article Section',
            },
        ),
        migrations.CreateModel(
            name='InsightArticleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='insight/articles/', validators=[home.validators.validate_image_size, home.validators.validate_image_extension])),
                ('date_label', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_entries', to='insight.insightarticlesection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
