# Generated by Django 5.2.13 on 2026-05-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_insightarticlesection_insightarticlecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightLaneSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Insight Lane Section',
                'verbose_name_plural': 'Insight Lane Section',
            },
        ),
        migrations.CreateModel(
            name='InsightLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_entries', to='insight.insightlanesection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
