# Generated by Django 5.2.13 on 2026-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_insightlanesection_insightlane'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightSubscribeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email_placeholder', models.CharField(blank=True, max_length=120)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('bottom_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Insight Subscribe Section',
                'verbose_name_plural': 'Insight Subscribe Section',
            },
        ),
    ]
